/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#1b1c1a",
        "tertiary": "#372508",
        "primary": "#002f20",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#404944",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e4e2df",
        "on-background": "#1b1c1a",
        "outline": "#707973",
        "on-tertiary": "#ffffff",
        "secondary-container": "#98f5c8",
        "surface-container": "#efeeeb",
        "secondary-fixed-dim": "#7cd8ad",
        "on-primary-fixed-variant": "#19503b",
        "outline-variant": "#c0c9c2",
        "on-secondary-fixed": "#002114",
        "surface-dim": "#dbdad7",
        "surface-bright": "#fbf9f6",
        "on-secondary-container": "#00734f",
        "secondary": "#006c4b",
        "on-tertiary-fixed": "#281800",
        "on-tertiary-fixed-variant": "#584323",
        "surface-container-high": "#eae8e5",
        "secondary-fixed": "#98f5c8",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#fedeb2",
        "primary-container": "#0d4733",
        "inverse-surface": "#30312f",
        "on-primary-fixed": "#002115",
        "on-secondary-fixed-variant": "#005137",
        "error": "#ba1a1a",
        "on-primary-container": "#7eb59b",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f2f0ed",
        "surface": "#fbf9f6",
        "primary-fixed": "#b6efd3",
        "tertiary-container": "#4f3b1c",
        "primary-fixed-dim": "#9bd2b7",
        "inverse-primary": "#9bd2b7",
        "on-tertiary-container": "#c2a57d",
        "surface-tint": "#336852",
        "background": "#fbf9f6",
        "surface-variant": "#e4e2df",
        "tertiary-fixed-dim": "#e0c298",
        "surface-container-low": "#f5f3f0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.75rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "margin": "2rem"
      },
      fontFamily: {
        "headline-lg": ["Noto Serif", "serif"],
        "headline-lg-mobile": ["Noto Serif", "serif"],
        "title-md": ["Be Vietnam Pro", "sans-serif"],
        "body-sm": ["Be Vietnam Pro", "sans-serif"],
        "headline-md": ["Noto Serif", "serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "label-sm": ["Be Vietnam Pro", "sans-serif"],
        "headline-sm": ["Noto Serif", "serif"],
        "display-hero-mobile": ["Noto Serif", "serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-quranic-mobile": ["Noto Serif", "serif"],
        "label-md": ["Be Vietnam Pro", "sans-serif"],
        "body-quranic": ["Noto Serif", "serif"],
        "display-hero": ["Noto Serif", "serif"],
        "headline-md-mobile": ["Noto Serif", "serif"]
      },
      fontSize: {
        "headline-lg": ["36px", { lineHeight: "54px", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "40px", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "44px", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "26px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "32px", fontWeight: "600" }],
        "display-hero-mobile": ["32px", { lineHeight: "48px", fontWeight: "700" }],
        "body-lg": ["17px", { lineHeight: "30px", fontWeight: "400" }],
        "body-quranic-mobile": ["20px", { lineHeight: "42px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-quranic": ["24px", { lineHeight: "50px", fontWeight: "500" }],
        "display-hero": ["48px", { lineHeight: "68px", fontWeight: "700" }],
        "headline-md-mobile": ["22px", { lineHeight: "36px", fontWeight: "600" }]
      }
    }
  },
  plugins: []
};
